/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Screens.Cadastros;

import Negocio.Servicos.Provider;
import javax.swing.JOptionPane;

/**
 *
 * @author dcet1-lami11-ubuntu
 */
public class Cadastro_Fornecedor extends javax.swing.JFrame {
    int xMouse, yMouse;

    /**
     * Creates new form Fornecedor
     */
    public Cadastro_Fornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        barra_ferramentas4 = new javax.swing.JPanel();
        panel_fechar4 = new javax.swing.JPanel();
        label_fechar4 = new javax.swing.JLabel();
        panel_minimizar = new javax.swing.JPanel();
        label_minimizar = new javax.swing.JLabel();
        label_nomeRestaurante = new javax.swing.JLabel();
        label_cadFornecedor = new javax.swing.JLabel();
        text_cnpj = new javax.swing.JFormattedTextField();
        icone_CNPJ = new javax.swing.JLabel();
        label_Gravar = new javax.swing.JLabel();
        label_salvar = new javax.swing.JLabel();
        label_cNPJ = new javax.swing.JLabel();
        label_nome = new javax.swing.JLabel();
        label_telefone = new javax.swing.JLabel();
        icone_nome = new javax.swing.JLabel();
        texto_nome = new javax.swing.JTextField();
        texto_telefone = new javax.swing.JFormattedTextField();
        icone_telefone = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkStartColor(new java.awt.Color(70, 0, 110));

        barra_ferramentas4.setBackground(new java.awt.Color(255, 255, 255));
        barra_ferramentas4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barra_ferramentas4MouseDragged(evt);
            }
        });
        barra_ferramentas4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barra_ferramentas4MousePressed(evt);
            }
        });

        panel_fechar4.setBackground(new java.awt.Color(255, 255, 255));
        panel_fechar4.setPreferredSize(new java.awt.Dimension(30, 30));

        label_fechar4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        label_fechar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_fechar4.setText("X");
        label_fechar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_fechar4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_fechar4Layout = new javax.swing.GroupLayout(panel_fechar4);
        panel_fechar4.setLayout(panel_fechar4Layout);
        panel_fechar4Layout.setHorizontalGroup(
            panel_fechar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fechar4Layout.createSequentialGroup()
                .addComponent(label_fechar4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_fechar4Layout.setVerticalGroup(
            panel_fechar4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_fechar4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panel_minimizar.setBackground(new java.awt.Color(255, 255, 255));

        label_minimizar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label_minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_minimizar.setText("-");

        javax.swing.GroupLayout panel_minimizarLayout = new javax.swing.GroupLayout(panel_minimizar);
        panel_minimizar.setLayout(panel_minimizarLayout);
        panel_minimizarLayout.setHorizontalGroup(
            panel_minimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_minimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        panel_minimizarLayout.setVerticalGroup(
            panel_minimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_minimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barra_ferramentas4Layout = new javax.swing.GroupLayout(barra_ferramentas4);
        barra_ferramentas4.setLayout(barra_ferramentas4Layout);
        barra_ferramentas4Layout.setHorizontalGroup(
            barra_ferramentas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barra_ferramentas4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_fechar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barra_ferramentas4Layout.setVerticalGroup(
            barra_ferramentas4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_fechar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_minimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        label_nomeRestaurante.setBackground(new java.awt.Color(204, 204, 204));
        label_nomeRestaurante.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        label_nomeRestaurante.setForeground(new java.awt.Color(204, 204, 204));
        label_nomeRestaurante.setText("Restaurante Lombinho de Porco II");
        label_nomeRestaurante.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label_cadFornecedor.setFont(new java.awt.Font("Ubuntu Light", 0, 20)); // NOI18N
        label_cadFornecedor.setForeground(new java.awt.Color(204, 204, 204));
        label_cadFornecedor.setText("Cadastro de Fornecedor");

        text_cnpj.setBorder(null);
        try {
            text_cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        icone_CNPJ.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        icone_CNPJ.setForeground(new java.awt.Color(204, 204, 204));
        icone_CNPJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screens/icons/icons8-login-arredondado-à-direita-25.png"))); // NOI18N

        label_Gravar.setBackground(new java.awt.Color(204, 204, 204));
        label_Gravar.setFont(new java.awt.Font("Ubuntu Light", 0, 18)); // NOI18N
        label_Gravar.setForeground(new java.awt.Color(204, 204, 204));
        label_Gravar.setText("Gravar");
        label_Gravar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screens/icons/icons8-salvar-35.png"))); // NOI18N
        label_salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_salvarMouseClicked(evt);
            }
        });

        label_cNPJ.setBackground(new java.awt.Color(204, 204, 204));
        label_cNPJ.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        label_cNPJ.setForeground(new java.awt.Color(204, 204, 204));
        label_cNPJ.setText("CNPJ");
        label_cNPJ.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label_nome.setBackground(new java.awt.Color(204, 204, 204));
        label_nome.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        label_nome.setForeground(new java.awt.Color(204, 204, 204));
        label_nome.setText("Nome");
        label_nome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label_telefone.setBackground(new java.awt.Color(204, 204, 204));
        label_telefone.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        label_telefone.setForeground(new java.awt.Color(204, 204, 204));
        label_telefone.setText("Telefone");
        label_telefone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        icone_nome.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        icone_nome.setForeground(new java.awt.Color(204, 204, 204));
        icone_nome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screens/icons/icons8-select-name-25.png"))); // NOI18N

        texto_nome.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        texto_nome.setBorder(null);
        texto_nome.setPreferredSize(new java.awt.Dimension(0, 15));
        texto_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_nomeActionPerformed(evt);
            }
        });

        texto_telefone.setBorder(null);
        try {
            texto_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        icone_telefone.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        icone_telefone.setForeground(new java.awt.Color(204, 204, 204));
        icone_telefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screens/icons/icons8-telefone-25.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screens/icons/icons8-produto-96.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barra_ferramentas4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(118, 118, 118))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(label_cadFornecedor))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(label_nomeRestaurante))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                    .addComponent(label_cNPJ)
                                    .addGap(95, 95, 95))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(label_nome)
                                        .addGap(93, 93, 93))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(icone_CNPJ)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                                .addGap(87, 87, 87)
                                                .addComponent(label_telefone)
                                                .addGap(81, 81, 81))
                                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(text_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, kGradientPanel1Layout.createSequentialGroup()
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(icone_nome)
                                            .addComponent(icone_telefone))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(texto_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(texto_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(label_Gravar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label_salvar)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(barra_ferramentas4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_nomeRestaurante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(label_cadFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(label_cNPJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(icone_CNPJ)
                    .addComponent(text_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icone_nome)
                    .addComponent(texto_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(label_telefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(texto_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icone_telefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_Gravar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void label_fechar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_fechar4MouseClicked
        Cadastro_Fornecedor.this.dispose();
    }//GEN-LAST:event_label_fechar4MouseClicked

    private void barra_ferramentas4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_ferramentas4MouseDragged
        // TODO add your handling code here:
        int X = evt.getXOnScreen();
        int Y = evt.getYOnScreen();
        this.setLocation(X - xMouse, Y - yMouse);
    }//GEN-LAST:event_barra_ferramentas4MouseDragged

    private void barra_ferramentas4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_ferramentas4MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barra_ferramentas4MousePressed

    private void label_salvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_salvarMouseClicked
        // TODO add your handling code here:
        Provider fornecedor0 = new Provider(text_cnpj.getText(), texto_nome.getText(), texto_telefone.getText());
        
        if(fornecedor0.Inserir())
            JOptionPane.showMessageDialog(null, "Fornecedor " + texto_nome.getText() + " inserido com sucesso! ");
        else
            JOptionPane.showMessageDialog(null, "Não foi possível completar a operação!");
                    
    }//GEN-LAST:event_label_salvarMouseClicked

    private void texto_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Fornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra_ferramentas4;
    private javax.swing.JLabel icone_CNPJ;
    private javax.swing.JLabel icone_nome;
    private javax.swing.JLabel icone_telefone;
    private javax.swing.JLabel jLabel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel label_Gravar;
    private javax.swing.JLabel label_cNPJ;
    private javax.swing.JLabel label_cadFornecedor;
    private javax.swing.JLabel label_fechar4;
    private javax.swing.JLabel label_minimizar;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_nomeRestaurante;
    private javax.swing.JLabel label_salvar;
    private javax.swing.JLabel label_telefone;
    private javax.swing.JPanel panel_fechar4;
    private javax.swing.JPanel panel_minimizar;
    private javax.swing.JFormattedTextField text_cnpj;
    private javax.swing.JTextField texto_nome;
    private javax.swing.JFormattedTextField texto_telefone;
    // End of variables declaration//GEN-END:variables
}
